# This workflow will apply the terraform scripts which would deploy the recquied infrastructure and the startup-sample-app

name: Terraform Apply

on:
  push:
    branches: [ main ]
    
env:
  TF_VERSION: 1.0.9
  environment: prod
  organization: bcgov
  SHA: ${{ github.sha }}
  GIT_URL: $GITHUB_SERVER_URL/$GITHUB_REPOSITORY	

  
jobs:
  build:

    runs-on: ubuntu-latest
        
    steps:
      - name: checkout the repo and building the Backend    
        uses: actions/checkout@v2
      
      
      - name: setting variables
        run: | 
             cd terraform/
             cat <<EOF > prod.auto.tfvars
             sha = "${{ env.SHA }}"
             git_url= "${{ env.GIT_URL }}"
             EOF
             
                                    
      
            

    
      - uses: hashicorp/setup-terraform@v1
        with:
            terraform_version: ${{ env.TF_VERSION }}
            cli_config_credentials_token: ${{ secrets.TFC_TEAM_TOKEN }}
            
          
            

      - name: Deploying startup-sample-project using terraform
        run: |
            cd terraform/
            cat <<EOF > backend.hcl
            organization = "${{ env.organization }}"
            workspaces { name = "${{ secrets.LICENCEPLATE }}-${{ env.environment }}-ssp-vm" }
            
            
            EOF
            
            terraform init -backend-config=backend.hcl
            
            terraform apply -auto-approve 
